services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-app
    container_name: laravel-app
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    networks:
      - laravel-network
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: laravel-db
    environment:
      MYSQL_DATABASE: 77sol_db
      MYSQL_ROOT_PASSWORD: i*{HG%Ity[WK
      MYSQL_USER: seven_seven
      MYSQL_PASSWORD: rax}GbZw?Ywa
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel-network
networks:
  laravel-network:
    driver: bridge

volumes:
  dbdata: