services:
  db:
    image: mysql:8.0
    container_name: laravel-db
    environment:
      MYSQL_DATABASE: 77sol_db
      MYSQL_ROOT_PASSWORD: i*{HG%Ity[WK
      MYSQL_USER: seven_seven
      MYSQL_PASSWORD: rax}GbZw?Ywa
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: ebersoncosme/laravel-app
    container_name: laravel-app
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    networks:
      - laravel-network
    depends_on:
      - db
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: 77sol_db
      DB_USERNAME: root
      DB_PASSWORD: i*{HG%Ity[WK
      APP_ENV: local
      APP_DEBUG: true
    command: >
      sh -c "composer install &&
             php artisan migrate --seed &&
             cp .env.example .env &&
             php artisan key:generate &&
             apache2-foreground &&
             chown -R www-data:www-data /var/www/html"

networks:
  laravel-network:
    driver: bridge

volumes:
  dbdata:
